spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calendar_db
    username: calendar_user
    password: calendar_password
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/cloudify