spring:
  application:
    name: calendar

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}

  liquibase:
    enabled: true
    liquibase-schema: ${LIQUIBASE_SCHEMA}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI}
          jwk-set-uri: ${OAUTH_JWK_SET_URI}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

logging:
  level:
    org.springframework.security: INFO
    com.calendar.app: DEBUG

server:
  port: 8080
  error:
    include-message: always